spring:
  datasource:
    url: jdbc:mysql://rm-wz9icd85l8kbklqth6o.mysql.rds.aliyuncs.com/saas_pinplatform?useSSL=false&characterEncoding=utf-8
    username: saas_dev
    password: wLAtkUxbbAajZm4A
  redis:
    host: 172.18.239.251
    port: 26379
    database: 5
