spring:
  datasource:
    url: jdbc:mysql://rm-wz9icd85l8kbklqth6o.mysql.rds.aliyuncs.com:3306/saas_wechatpay?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: saas_dev
    password: wLAtkUxbbAajZm4A

  redis:
    host: 172.18.239.251
    port: 26379
    database: 3
